const Activity = './icon/mdg/0.Activity.bmp'
const Control_flow = './icon/mdg/0.Control_flow.bmp'

export const StateMachineToolSet = [
  {
    Group: 'SysML State',
    GroupAlias: 'SysML State',
    items: [
      {
        id: 'UML4SysML::State',
        Object_Type: 'State',
        Stereotype: 'State',
        title: 'State',
        value: 'State',
        idSeed: 1,
        icon: Activity,
        width: 160,
        height: 80,
        nodeType: 'rectangle',
        dropAble: true, // 是否可以作为drop的对象
        style: {
          shape: 'rect',
          html: 1,
          arcSize: 22,
          rotatable: 0,
          absoluteArcSize: 1,
          rounded: 1,
          whiteSpace: 'wrap',
          align: 'center',
          fillColor: '#fde1af',
          strokeColor: '#000000',
        },
      },
      {
        id: 'UML4SysML::Initial',
        Object_Type: 'StateNode',
        Stereotype: 'Initial',
        NType: 3,
        title: 'Initial',
        value: 'Initial',
        idSeed: 1,
        icon: './icon/mdg/0.Inital.bmp',
        width: 20,
        height: 20,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          aspect: 'fixed',
          shape: 'ellipse',
          fillColor: 'strokeColor',
          html: 1,
          strokeColor: '#000000',
          labelPosition: 'center',
          verticalLabelPosition: 'bottom',
          align: 'center',
          verticalAlign: 'top',
        },
      },
      {
        id: 'UML4SysML::Final',
        Object_Type: 'StateNode',
        Stereotype: 'Final',
        NType: 4,
        title: 'Final',
        value: 'Final',
        idSeed: 1,
        icon: './icon/mdg/0.Final.bmp',
        width: 20,
        height: 20,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          aspect: 'fixed',
          verticalLabelPosition: 'bottom',
          html: 1,
          verticalAlign: 'top',
          strokeWidth: 1,
          shape: 'mxgraph.lean_mapping.sequenced_pull_ball',
          fillColor: '#c4dd92',
          strokeColor: '#000000',
        },
      },
      {
        id: 'UML4SysML::Choice',
        Object_Type: 'StateNode',
        Stereotype: 'Choice',
        NType: 11,
        title: 'Choice',
        value: 'Choice',
        idSeed: 1,
        icon: './icon/mdg/0.Choice.bmp',
        width: 26,
        height: 34,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          shape: 'rhombus',
          html: 1,
          dashed: 0,
          whiteSpace: 'wrap',
          perimeter: 'rhombusPerimeter',
          fillColor: '#c4dd92',
          strokeColor: '#000000',
          labelPosition: 'center',
          verticalLabelPosition: 'top',
          align: 'center',
          verticalAlign: 'top',
        },
      },
      {
        id: 'UML4SysML::History',
        Object_Type: 'StateNode',
        Stereotype: 'History',
        NType: 5,
        title: 'History',
        value: 'History',
        idSeed: 1,
        icon: './icon/mdg/0.History.bmp',
        width: 20,
        height: 20,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          aspect: 'fixed',
          shape: 'ellipse',
          whiteSpace: 'wrap',
          html: 1,
          fillColor: '#c4dd92',
          strokeColor: '#000000',
          labelPosition: 'center',
          verticalLabelPosition: 'bottom',
          align: 'center',
          verticalAlign: 'top',
        },
      },
      {
        id: 'UML4SysML::Junction',
        Object_Type: 'StateNode',
        Stereotype: 'Junction',
        NType: 10,
        title: 'Junction',
        value: 'Junction',
        idSeed: 1,
        icon: './icon/mdg/0.Junction.bmp',
        width: 20,
        height: 20,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          aspect: 'fixed',
          shape: 'ellipse',
          fillColor: 'strokeColor',
          html: 1,
          strokeColor: '#000000',
          labelPosition: 'center',
          verticalLabelPosition: 'bottom',
          align: 'center',
          verticalAlign: 'top',
        },
      },
      {
        id: 'UML4SysML::Entry',
        Object_Type: 'StateNode',
        Stereotype: 'Entry',
        NType: 13,
        title: 'Entry',
        value: 'Entry',
        idSeed: 1,
        icon: './icon/mdg/0.Entry.bmp',
        width: 20,
        height: 20,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          aspect: 'fixed',
          shape: 'ellipse',
          whiteSpace: 'wrap',
          html: 1,
          fillColor: '#C4DD92',
          strokeColor: '#000000',
          labelPosition: 'center',
          verticalLabelPosition: 'bottom',
          align: 'center',
          verticalAlign: 'top',
        },
      },
      {
        id: 'UML4SysML::Exit',
        Object_Type: 'StateNode',
        Stereotype: 'Exit',
        NType: 14,
        title: 'Exit',
        value: 'Exit',
        idSeed: 1,
        icon: './icon/mdg/0.Exit.bmp',
        width: 20,
        height: 20,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          aspect: 'fixed',
          shape: 'sumEllipse',
          perimeter: 'ellipsePerimeter',
          whiteSpace: 'wrap',
          html: 1,
          backgroundOutline: 1,
          fillColor: '#C4DD92',
          strokeColor: '#000000',
          labelPosition: 'center',
          verticalLabelPosition: 'bottom',
          align: 'center',
          verticalAlign: 'top',
        },
      },
      {
        id: 'UML4SysML::Terminate',
        Object_Type: 'Terminate',
        Stereotype: 'Terminate',
        NType: 12,
        title: 'Terminate',
        value: 'Terminate',
        idSeed: 1,
        icon: './icon/mdg/0.Terminate.bmp',
        width: 20,
        height: 20,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          aspect: 'fixed',
          shape: 'umlDestroy',
          html: 1,
          strokeColor: '#000000',
          fillColor: 'none',
          labelPosition: 'center',
          verticalLabelPosition: 'bottom',
          align: 'center',
          verticalAlign: 'top',
        },
      },
    ],
  },
  {
    Group: 'SysML State Relationships',
    GroupAlias: 'SysML State Relationships',
    items: [
      {
        id: 'UML4SysML::Transition',
        Object_Type: 'Transition',
        Stereotype: 'Transition',
        title: 'Transition',
        value: '',
        Connector_Type: 'StateFlow',
        idSeed: 1,
        icon: Control_flow,
        width: 1,
        isEdge: true,
        isPort: false,
        nodeType: 'link',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          endArrow: 'open',
          html: 1,
          rounded: 0,
          endSize: 12,
          strokeColor: '#000000',
        },
      },
      {
        id: 'UML4SysML::Abstraction',
        Object_Type: 'Abstraction',
        Stereotype: 'Abstraction',
        title: 'Abstraction',
        Connector_Type: 'Abstraction',
        idSeed: 1,
        icon: Control_flow,
        width: 1,
        isEdge: true,
        isPort: false,
        nodeType: 'link',
        value: '《abstraction》',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          endArrow: 'open',
          html: 1,
          rounded: 0,
          strokeColor: '#000000',
          endFill: 0,
          startSize: 6,
          endSize: 10,
          dashed: 1,
        },
      },
      {
        id: 'UML4SysML::Dependency',
        Object_Type: 'Dependency',
        Stereotype: 'Dependency',
        title: 'Dependency',
        Connector_Type: 'Dependency',
        value: '',
        idSeed: 1,
        icon: Control_flow,
        width: 1,
        isEdge: true,
        isPort: false,
        nodeType: 'link',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          endArrow: 'open',
          html: 1,
          rounded: 0,
          strokeColor: '#000000',
          endFill: 0,
          startSize: 6,
          endSize: 10,
          dashed: 1,
        },
      },
      {
        id: 'UML4SysML::Realisation',
        Object_Type: 'Realisation',
        Stereotype: 'Realisation',
        title: 'Realisation',
        Connector_Type: 'Realisation',
        value: '',
        idSeed: 1,
        icon: Control_flow,
        width: 1,
        isEdge: true,
        isPort: false,
        nodeType: 'link',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          endArrow: 'blockThin',
          html: 1,
          rounded: 0,
          labelBackgroundColor: 'default',
          strokeColor: '#000000',
          align: 'center',
          verticalAlign: 'middle',
          fontFamily: 'Helvetica',
          fontSize: 11,
          fontColor: 'default',
          endSize: 16,
          shape: 'connector',
          jumpStyle: 'none',
          endFill: 0,
          dashed: 1,
        },
      },
    ],
  },
  {
    Group: 'SysML Additional',
    GroupAlias: 'SysML Additional',
    items: [
      {
        id: 'UML4SysML::Object',
        Object_Type: 'Object',
        Stereotype: 'Object',
        title: 'Object',
        value: 'Object',
        idSeed: 1,
        icon: './icon/mdg/0.Object_node.bmp',
        width: 90,
        height: 50,
        nodeType: 'rectangle',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          shape: 'rect',
          html: 1,
          arcSize: 4,
          rotatable: 0,
          absoluteArcSize: 1,
          rounded: 1,
          whiteSpace: 'wrap',
          align: 'center',
          fillColor: '#C7EDEF',
          strokeColor: '#000000',
          verticalAlign: 'top',
          fontStyle: 4,
        },
      },
      {
        id: 'UML4SysML::Event',
        Object_Type: 'Event',
        Stereotype: 'Event',
        title: 'Event',
        value: 'Event',
        idSeed: 1,
        icon: './icon/mdg/0.Event.bmp',
        width: 70,
        height: 40,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          shape: 'mxgraph.sysml.sendSigAct',
          html: 1,
          whiteSpace: 'wrap',
          align: 'center',
          fillColor: '#FAB4B0',
          strokeColor: '#000000',
        },
      },
      {
        id: 'UML4SysML::Signal',
        Object_Type: 'Signal',
        Stereotype: 'Signal',
        title: 'Signal',
        value: 'Signal',
        idSeed: 1,
        icon: './icon/mdg/0.Signal.bmp',
        width: 90,
        height: 70,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          shape: 'rect',
          html: 1,
          arcSize: 4,
          rotatable: 0,
          absoluteArcSize: 1,
          rounded: 1,
          whiteSpace: 'wrap',
          align: 'center',
          fillColor: '#FFFFFF',
          strokeColor: '#000000',
          verticalAlign: 'top',
          fontStyle: 4,
        },
      },
      {
        id: 'UML4SysML::Trigger',
        Object_Type: 'Trigger',
        Stereotype: 'Trigger',
        title: 'Trigger',
        value: 'Trigger',
        idSeed: 1,
        icon: './icon/mdg/0.Trigger.bmp',
        width: 70,
        height: 40,
        nodeType: 'ellipse',
        dropAble: false, // 是否可以作为drop的对象
        style: {
          shape: 'mxgraph.sysml.sendSigAct',
          html: 1,
          whiteSpace: 'wrap',
          align: 'center',
          fillColor: '#D7F9F9',
          strokeColor: '#000000',
        },
      },
    ],
  },
]
